format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$golang\
$python\
$rust\
$cmd_duration\
$line_break\
$status\
$shell\
$character"""

[directory]
truncation_length = 8
truncate_to_repo = false
